steps:
- name: 'gcr.io/cloud-builders/git'
  id: Replace environment variabels
  volumes:
  - name: 'manifestsvolume'
    path: '/data'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed "s/£CKAN_API_KEY/${_CKAN_API_KEY}/g" facade/deployment.yaml > /data/deployment.yaml
    sed -i "s#£API_URL#${_CKAN_API_URL}#g" /data/deployment.yaml
    sed -i "s/£FACADE_SECRET_KEY/${_FACADE_SECRET_KEY}/g" /data/deployment.yaml
    sed -i "s/£GOV_NOTIFY_PUBLISHER_REQUEST_TEMPLATE_ID/${_GOV_NOTIFY_PUBLISHER_REQUEST_TEMPLATE_ID}/g" /data/deployment.yaml
    sed -i "s/£GOV_NOTIFY_PUBLISHER_REQUEST_EMAIL_TO/${_GOV_NOTIFY_PUBLISHER_REQUEST_EMAIL_TO}/g" /data/deployment.yaml
    sed -i "s/£GOV_NOTIFY_KEY/${_GOV_NOTIFY_KEY}/g" /data/deployment.yaml
    sed -i "s/£GOV_NOTIFY_CONTACT_PAGE_TEMPLATE_ID/${_GOV_NOTIFY_CONTACT_PAGE_TEMPLATE_ID}/g" /data/deployment.yaml
    sed -i "s/£GOV_NOTIFY_CONTACT_INFO_EMAIL_TO/${_GOV_NOTIFY_CONTACT_INFO_EMAIL_TO}/g" /data/deployment.yaml
    sed -i "s#£FACADE_SEQUELIZE_URL#${_FACADE_SEQUELIZE_URL}#g" /data/deployment.yaml
    sed "s#_DOMAINNAME#${_DOMAINNAME}#g" facade/certificate.yaml > /data/certificate.yaml
    sed -i "s#_WORKLOAD_SVC_ACCT#${_WORKLOAD_SVC_ACCT}#g" facade/ckanserviceaccount.yaml
    sed -i "s#_CONNECTIONNAME#${_CONNECTIONNAME}#g" facade/connectionname_configmap.yaml
    sed -i "s#_CLOUDSQL_RESOURCE_NAME#${_CLOUDSQL_RESOURCE_NAME}#g" facade/cloudsql-secrets.yaml
    cp facade/ingress.yaml /data/ingress.yaml
    cp facade/service.yaml /data/service.yaml
    cp facade/cloudsql-secrets.yaml /data/cloudsql-secrets.yaml
    cp facade/ckanserviceaccount.yaml /date/ckanserviceaccount.yaml
    cp facade/cloudsql-secrets.yaml /data/cloudsql-secrets.yaml
    cp facade/facade-pvc.yaml /data/facade-pvc.yaml

- name: "gcr.io/cloud-builders/gke-deploy"
  volumes:
    - name: 'manifestsvolume'
      path: '/data'
  args:
  - run
  - --filename=/data/
  - --location=europe-west2
  - --namespace=${_NAMESPACE}
  - --cluster=${_CLUSTER}
  timeout: 600s

substitutions:
    _NAMESPACE: kits-dft-test
    _CLUSTER: kits-dft-test-cluster
