apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudsql-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "_CLOUDSQL_RESOURCE_NAME"
        path: "key.json"
