apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: facade-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
